name: Upload image(s)
description: Upload images to share on Zooniverse Talk (auto-processed)
title: "Upload: short description"
labels: ["upload"]
body:
  - type: markdown
    attributes:
      value: |
        **How to use**
        - Drag 1–5 images into the box below (JPG/PNG/WebP).
        - Add optional alt-text / caption.
        - Submit. In ~1 minute the bot will reply with ready-to-paste links.
  - type: textarea
    id: images
    attributes:
      label: Drag & drop images here
      description: You can paste multiple files.
      placeholder: Drop files or paste them; GitHub will attach and inline links.
    validations:
      required: true
  - type: input
    id: alt
    attributes:
      label: Alt text / caption (optional)
      placeholder: e.g., “Edge-on galaxy with dust lane”
  - type: dropdown
    id: license
    attributes:
      label: License confirmation
      options:
        - "I confirm I have rights to share these images under CC BY 4.0"
        - "I cannot confirm (do not submit)"
    validations:
      required: true
