name: Ingest Issue Uploads
on:
  issues:
    types: [opened]
permissions:
  contents: write
  issues: write
jobs:
  ingest:
    if: contains(github.event.issue.labels.*.name, 'upload')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pillow requests pyyaml

      - name: Ingest images from issue
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_AUTHOR: ${{ github.event.issue.user.login }}
          REPO: ${{ github.repository }}
        run: |
          python .github/workflows/ingest_from_issue.py

      - name: Commit processed images
        run: |
          git config user.name "upload-bot"
          git config user.email "upload-bot@users.noreply.github.com"
          git add images/ images/index.json metadata/ || true
          if ! git diff --cached --quiet; then
            git commit -m "Ingest images from #${{ github.event.issue.number }}"
            git push
          fi

      - name: Comment links back on issue
        env:
          GH_TOKEN: ${{ github.token }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
        run: |
          python .github/workflows/comment_links.py
