name: Process Talk Images
on:
  push:
    paths:
      - 'incoming/**'
      - 'metadata/**'
      - '.github/workflows/process-images.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pillow pyyaml

      - name: Process images
        run: |
          python .github/workflows/process_images.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add images/ && git add metadata/alt-text.yaml || true
          if ! git diff --cached --quiet; then
            git commit -m "Process images: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No changes to commit."
          fi
